site_name: Dive Into IC Design
site_description: This is a sample documentation site with various features and configurations.
site_author: Fengfan Liu

# Navigation configuration
nav:
  - Home: index.md
  # Chapter 1
  - "Chapter 1: Overview":
    - "What is this book about?": "chapter_1_Overview/what.md"
    - "How to read this book?": "chapter_1_Overview/how.md"
  # Chapter x
  - "Chapter x: Module Verification":
    - "What work is required for Module Verification?": "chapter_x_Module_Verification/what.md"
    - "Test Plan Template": "chapter_x_Module_Verification/test_plan_template.md"
    - "Write test plan": "chapter_x_Module_Verification/write_test_plan.md"
    - "Review test plan": "chapter_x_Module_Verification/review_test_plan.md"
    - "Test Bench Template":
      - "Test Plan Template": "chapter_x_Module_Verification/test_bench_template/test_bench_template.md"
      - "Agent": "chapter_x_Module_Verification/test_bench_template/agent.md"
      - "Env": "chapter_x_Module_Verification/test_bench_template/env.md"
  # Chapter x
  - "Chapter x: Top Verification":
    - "What work is required for TOP Verification?": "chapter_x_Top_Verification/what.md"

# Theme configuration
theme:
  name: readthedocs
