site_name: Dive Into IC Design
site_description: This is a sample documentation site with various features and configurations.
site_author: Fengfan Liu

# Navigation configuration
nav:
  - Home: index.md
  - "Chapter 1: Overview":
    - "What is this book about?": "chapter_1_Overview/what.md"
    - "How to read this book?":   "chapter_1_Overview/how.md"
  - "Chapter x: Top Verification":
    - "What work is required for TOP Verification?": "chapter_x_Top_Verification/what.md"

# Theme configuration
theme:
  name: readthedocs
